@startuml
'https://plantuml.com/class-diagram

entity Meal {
    +id : Long
    +mealId : String
    +name : String
    +category : String
    +area : String
    +instructions : String
    +imageUrl : String
}

entity Ingredient {
    +id : Long
    +ingredientName : String
}

entity Workout {
    +id : Long
    +workoutId : String
    +name : String
    +category : String
    +description : String
}

Meal ||--o{ Ingredient : contains
@enduml
