### LOGIN (get JWT)
POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "password"
}

### GET meals (token required)
# Replace <PASTE_TOKEN_HERE> with the JWT from the login response
GET http://localhost:8081/api/meals
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc0MzUzNDA1NiwiZXhwIjoxNzQzNTM3NjU2fQ.KXBJ6ajn4NAJAoKp3RFJZiXeuhUGqR43X3PYY5-0vPM

### GET meals (token required)
GET http://142.93.108.228:8081/api/meals
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc0MzU0MTI2NSwiZXhwIjoxNzQzNTQ0ODY1fQ.vOqrF5xvtRm_ryJFgITEgsVQxa_R2_CmaaeTyY_UiXA


### POST a random meal (admin only)
POST http://localhost:8081/api/meals
Authorization: Bearer <PASTE_TOKEN_HERE>

### GET workouts (token required)
GET http://localhost:8081/workouts
Authorization: Bearer <PASTE_TOKEN_HERE>


//Token was accepted
✔️ Role ADMIN was correctly extracted
✔️ Controller returned the list of meals
✔️ Serialization worked (no recursion, no lazy init crash)
✔️ Response code 200 OK
✔️ Your fetchAndSaveMultipleMeals() is running as expected

//### LOGIN (get JWT)
POST http://142.93.108.228:8081/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "password"
}
